//測試
export const SET_TEST = "SET_TEST";
export const RESET_TEST = "RESET_TEST";
export const LOGIN = "LOGIN";
export const STORE_USER_INFO="STORE_USER_INFO";

export const SAVE_TRANS_DATA="SAVE_TRANS_DATA";
export const SAVE_DAILYRATES="SAVE_DAILYRATES";
export const SAVE_QUARTERRATES="SAVE_QUARTERRATES";
export const SAVE_MONTHLYRATES="SAVE_MONTHLYRATES";