//測試
export const SET_TEST = "SET_TEST";
export const RESET_TEST = "RESET_TEST";
export const LOGIN = "LOGIN";
export const STORE_USER_INFO = "STORE_USER_INFO";

export const SAVE_TRANS_DATA = "SAVE_TRANS_DATA";
export const SAVE_DAILYRATES = "SAVE_DAILYRATES";
export const SAVE_DAILYKNNRATES = "SAVE_DAILYKNNRATES";
export const SAVE_DAILYTENRATES = "SAVE_DAILYTENRATES";


export const SAVE_QUARTERRATES = "SAVE_QUARTERRATES";
export const SAVE_QUARTERKNNRATES = "SAVE_QUARTERKNNRATES";
export const SAVE_QUARTERTENRATES = "SAVE_QUARTERTENRATES";


export const SAVE_MONTHLYRATES = "SAVE_MONTHLYRATES";
export const SAVE_MONTHLYKNNRATES = "SAVE_MONTHLYKNNRATES";
export const SAVE_MONTHLYTENRATES = "SAVE_MONTHLYTENRATES";
export const SAVE_MONTHLYGUARTRATES = "SAVE_MONTHLYGUARTRATES";


export const SAVE_EACHTRANSINFO = "SAVE_EACHTRANSINFO";
export const SAVE_ABN_TRANS_DATA = "SAVE_ABN_TRANS_DATA";
export const SAVE_USER_LIST_API = "SAVE_USER_LIST_API"
export const SAVE_USER_LIST_EDIT= "SAVE_USER_LIST_EDIT"


